export const HEXOBJECT_KEYS = {
  TREE: 'tree',
  COINS: 'coins',
  ROCK: 'rock',
  SKELETOR: 'skeletor',
  EMITTER: 'emitter',
  INFERNO: 'inferno',
  AXE: 'axe',
  HAND: 'hand',
  PICKAXE: 'pickaxe',
  SWORD: 'sword',
  SHIELD: 'shield',
  CAMPING_ENTRANCE: 'camping-entrance',
  CAVE_ENTRANCE: 'cave-entrance',
  HOMELAND_GATE: 'homeland-gate',
  HEALTH_BOTTLE: 'health-bottle',
  ENERGY_BOTTLE: 'energy-bottle',
  MANA_BOTTLE: 'mana-bottle',
  FIREPLACE: 'fireplace',
  HEALING_SPRING: 'healing-spring',
  WOOD_AND_LEAVES: 'wood-and-leaves',
  GRAVE: 'grave',
  CHEST: 'chest',
} as const;

export type THexobjectKey = (typeof HEXOBJECT_KEYS)[keyof typeof HEXOBJECT_KEYS];
