import type { WorldSectionDef } from './world-section-schema';

export const WORLD_SECTIONS: WorldSectionDef[] = [
  {
    key: 'camp-anchor',
    tags: ['CAMP_ANCHOR'],
    allowRotation: false,
    weight: 1,
    hexes: [
      { q: 0, r: 0, terrain: 'OPEN_GROUND' },
      { q: 1, r: 0, terrain: 'OPEN_GROUND' },
      { q: 0, r: 1, terrain: 'OPEN_GROUND' },
      { q: -1, r: 0, terrain: 'OPEN_GROUND' },
      { q: 1, r: -1, terrain: 'OPEN_GROUND' },
    ],
    seams: [
      { q: 1, r: 0, dir: 0 },
      { q: -1, r: 0, dir: 3 },
      { q: 0, r: 1, dir: 5 },
    ],
  },
  {
    key: 'fork',
    tags: ['BRANCH'],
    allowRotation: true,
    weight: 3,
    hexes: [
      { q: 0, r: 0, terrain: 'OPEN_GROUND' },
      { q: 1, r: 0, terrain: 'OPEN_GROUND' },
      { q: 2, r: 0, terrain: 'OPEN_GROUND' },
      { q: -1, r: 1, terrain: 'OPEN_GROUND' },
      { q: 0, r: -1, terrain: 'OPEN_GROUND' },
    ],
    seams: [
      { q: 2, r: 0, dir: 0 },
      { q: -1, r: 1, dir: 4 },
      { q: 0, r: -1, dir: 2 },
    ],
  },
  {
    key: 'open-field',
    tags: ['OPEN_AREA'],
    allowRotation: true,
    weight: 4,
    hexes: [
      { q: 0, r: 0, terrain: 'OPEN_GROUND' },
      { q: 1, r: 0, terrain: 'OPEN_GROUND' },
      { q: 2, r: 0, terrain: 'OPEN_GROUND' },
      { q: 0, r: 1, terrain: 'OPEN_GROUND' },
      { q: 1, r: 1, terrain: 'OPEN_GROUND' },
      { q: 2, r: 1, terrain: 'OPEN_GROUND' },
      { q: 1, r: -1, terrain: 'OPEN_GROUND' },
      { q: 1, r: 2, terrain: 'OPEN_GROUND' },
    ],
    seams: [
      { q: 0, r: 0, dir: 3 },
      { q: 2, r: 0, dir: 0 },
      { q: 1, r: 2, dir: 5 },
      { q: 1, r: -1, dir: 2 },
    ],
  },
  {
    key: 'forest-clearing',
    tags: ['OPEN_AREA'],
    allowRotation: true,
    weight: 3,
    hexes: [
      { q: 0, r: 0, terrain: 'OPEN_GROUND' },
      { q: 1, r: 0, terrain: 'FOREST_EDGE' },
      { q: 2, r: 0, terrain: 'FOREST_EDGE' },
      { q: 0, r: 1, terrain: 'FOREST_EDGE' },
      { q: 1, r: 1, terrain: 'FOREST_EDGE' },
      { q: -1, r: 1, terrain: 'FOREST_EDGE' },
    ],
    seams: [
      { q: 2, r: 0, dir: 0 },
      { q: -1, r: 1, dir: 3 },
      { q: 1, r: 1, dir: 5 },
    ],
  },
  {
    key: 'narrow-pass',
    tags: ['CHOKEPOINT'],
    allowRotation: true,
    weight: 2,
    hexes: [
      { q: 0, r: 0, terrain: 'NARROW_PASS' },
      { q: 1, r: 0, terrain: 'NARROW_PASS' },
      { q: 2, r: 0, terrain: 'NARROW_PASS' },
      { q: 3, r: 0, terrain: 'NARROW_PASS' },
    ],
    seams: [
      { q: 0, r: 0, dir: 3 },
      { q: 3, r: 0, dir: 0 },
    ],
  },
  {
    key: 'stone-ridge',
    tags: ['BARRIER'],
    allowRotation: true,
    weight: 2,
    hexes: [
      { q: 0, r: 0, terrain: 'STONE_RIDGE' },
      { q: 0, r: 1, terrain: 'STONE_RIDGE' },
      { q: 0, r: 2, terrain: 'STONE_RIDGE' },
      { q: 1, r: -1, terrain: 'OPEN_GROUND' },
      { q: 1, r: 0, terrain: 'OPEN_GROUND' },
      { q: 1, r: 1, terrain: 'OPEN_GROUND' },
      { q: 1, r: 2, terrain: 'OPEN_GROUND' },
    ],
    seams: [
      { q: 1, r: -1, dir: 2 },
      { q: 1, r: 2, dir: 5 },
    ],
  },
  {
    key: 'broken-slope',
    tags: ['BARRIER', 'CHOKEPOINT'],
    allowRotation: true,
    weight: 2,
    hexes: [
      { q: 0, r: 0, terrain: 'BROKEN_GROUND' },
      { q: 1, r: 0, terrain: 'BROKEN_GROUND' },
      { q: 1, r: 1, terrain: 'BROKEN_GROUND' },
      { q: 2, r: 1, terrain: 'BROKEN_GROUND' },
      { q: 2, r: 2, terrain: 'BROKEN_GROUND' },
    ],
    seams: [
      { q: 0, r: 0, dir: 3 },
      { q: 2, r: 2, dir: 5 },
    ],
  },
  {
    key: 'side-pocket',
    tags: ['POCKET'],
    allowRotation: true,
    weight: 2,
    hexes: [
      { q: 0, r: 0, terrain: 'POCKET_FLOOR' },
      { q: 1, r: 0, terrain: 'POCKET_FLOOR' },
      { q: 1, r: 1, terrain: 'POCKET_FLOOR' },
      { q: 0, r: 1, terrain: 'POCKET_FLOOR' },
    ],
    seams: [{ q: 0, r: 0, dir: 3 }],
  },
  {
    key: 'sheltered-pocket',
    tags: ['POCKET'],
    allowRotation: true,
    weight: 1,
    hexes: [
      { q: 0, r: 0, terrain: 'POCKET_FLOOR' },
      { q: 1, r: 0, terrain: 'POCKET_FLOOR' },
      { q: 2, r: 0, terrain: 'POCKET_FLOOR' },
      { q: 1, r: 1, terrain: 'POCKET_FLOOR' },
      { q: 1, r: -1, terrain: 'POCKET_FLOOR' },
    ],
    seams: [{ q: 0, r: 0, dir: 3 }],
  },
  {
    key: 'frontier-shelf',
    tags: ['FRONTIER'],
    allowRotation: true,
    weight: 2,
    hexes: [
      { q: 0, r: 0, terrain: 'FRONTIER_EDGE' },
      { q: 1, r: 0, terrain: 'FRONTIER_EDGE' },
      { q: 2, r: 0, terrain: 'FRONTIER_EDGE' },
      { q: 1, r: 1, terrain: 'FRONTIER_EDGE' },
    ],
    seams: [
      { q: 0, r: 0, dir: 3 },
      { q: 2, r: 0, dir: 0 },
    ],
  },
];
